const products = [
        {
        "id": 1,
        "name": "Brown Chair",
        "image": "imgs/chair-2.png",
        "description": "An Elegant Chair",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Furniture',
        "oldPrice" : '30',
        "price": '25',
    },
    {
        "id": 2,
        "name": "Women's Shirt",
        "image": "imgs/dress.png",
        "description": "Gorgeous Women's Shirt",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Clothes',
        "oldPrice" : '15',
        "price": '10',
    },
    {
        "id": 3,
        "name": "Watch",
        "image": "imgs/watch.jpg",
        "description": "Smart Watch",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Electronics',
        "oldPrice" : '50',
        "price": '37',
    },
    {
        "id": 4,
        "name": "Earbuds",
        "image": "imgs/earbuds.png",
        "description": "Bady Blue Earbuds",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Electronics',
        "oldPrice" : '20',
        "price": '12',
    },
    {
        "id": 5,
        "name": "T-Shirt",
        "image": "imgs/t-shirt.png",
        "description": "Children's T-Shirt",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Clothes',
        "oldPrice" : '10',
        "price": '7',
    },
    {
        "id": 6,
        "name": "Women's Shoes",
        "image": "imgs/women's-shoes.png",
        "description": "Beautiful Women's Shoes",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Clothes',
        "oldPrice" : '23',
        "price": '16',
    },
    {
        "id": 7,
        "name": "Blue Chair",
        "image": "imgs/chair.png",
        "description": "A Sturdy Chair",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Furniture',
        "oldPrice" : '40',
        "price": '35',
    },
    {
        "id": 8,
        "name": "Phone",
        "image": "imgs/phone.png",
        "description": "Apple Phone",
        "about" : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusantium reprehenderit sed alias dicta provident? Obcaecati, natus. Nihil inventore et totam illum, eum magnam. Quaerat esse tempore corporis odit similique minus!',
        "category" : 'Electronics',
        "oldPrice" : '200',
        "price": '177',
    },

]

// localStorage.setItem('products', JSON.stringify(products))